description: 'TensorFlow ResNet IMAGENET'
output_dir: logs/tensorflow-resnet50-imagenet.${NUM_NODES}.${SLURM_JOB_ID}
data:
    name: imagenet
    path: /work/staff/nikoloutsa/data

model:
    name: resnet50
    input_shape: [224, 224, 3]
    n_classes: 1000

optimizer:
    name: SGD
    lr: 0.001
    momentum: 0.9
    lr_scaling: linear

training:
    batch_size: 512
    n_epochs: 1
    lr_warmup_epochs: 0
    loss: categorical_crossentropy 
    metrics: [accuracy]
