description: 'TensorFlow ResNet CIFAR10'
output_dir: logs/tensorflow-resnet50-cifar10.${NUM_NODES}.${SLURM_JOB_ID}
data:
    name: cifar10

model:
    name: resnet50
    input_shape: [32, 32, 3]
    n_classes: 10

optimizer:
    name: SGD
    lr: 0.01
    lr_scaling: linear

training:
    batch_size: 64
    n_epochs: 60
    lr_warmup_epochs: 5
    loss: categorical_crossentropy 
    metrics: [accuracy]
